# Site Info
title: Guokas Blog
tagline: 'An Enthusiastic Programmer'
description: 'Guokas blog'
baseurl: ""
url: https://blog.guokas.top
logo: '/public/logo.png'
timezone: Asia/Shanghai

# Site configurations
remote_theme: pages-themes/time-machine@v0.2.0
gems:
  - jekyll-paginate
  - jekyll-sitemap  
plugins: [jekyll-paginate,jekyll-sitemap,jekyll-remote-theme]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 10
paginate_path: '/blog/page:num'
permalink: pretty

version: 2.0.0

# About/contact
author:
  name: Guokas
  description: A passionate <strong>developer and researcher</strong>, learning to be giant.
  gravatar: a2590617c567e9568d51e2ded184d225 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/guokas/
    github:    https://github.com/guokas
    # facebook:  <hide>
    twitter:   https://twitter.com/GuokasWu
    #weibo:     http://weibo.com/41173780
    #email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav: 
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  # Github Project: 
    # - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/liwenliang.jpg
  caption: <a href="https://en.wikipedia.org/wiki/Li_Wenliang">李文亮 & 1986-2020 </a> 
# Puglins
# mathjax: true # whether support mathjax
google_analytics_token: 'G-XL5GS8XF3K' # leave blank if you don't want google analytics(gtag.js)
disqus_short_name: 'guokas' # leave blank if you don't want disqus

category_links: 
  - { 'CSharp-EF', '../../csharp-ef/2020/02/28/Entitiy-Framework-Tutorial/' }
  - { 'CSharp-ASP.NET Core', '../../csharp-asp.net core/2020/04/27/asp-dot-net-core-tutorial/' }
  - { 'Docker', '../../docker/2020/07/08/docker-tutorial/'}
  - { 'Jenkins', '../../jenkins/2020/12/23/jenkins-tutorial/'}
  - { 'MSSQL', '../../mssql/2021/08/24/mssql-tutorial/'}
